pipeline{
    
    // agent any
    agent {
        label 'docker'
    }
    
//

    stages {
        stage('Clean Workspace') {
            steps {
                script {
                    cleanWs()
                    echo "Workspace cleaned."
                    sh """
                    sudo docker rm -f $(sudo docker ps -a -q)
                    """
                }
                echo "Docker containers removed."
            }
        }


        stage('Clone repo') {
            steps {
                script {
                    git branch: 'json-domain_baha', url: 'https://github.com/dorhs/project1.git'
                }
            }
        }
        stage('Docker build') {
            steps {
                dir('project1/DomainMonitoringSystemv1.0.4'){
                    script {
                        sh """
                        sudo docker build -t tpp:temp .
                        """
                    }
                }
            }
        }
        stage('Run container') {
            steps {
                script {
                    sh """
                    sudo docker run -p 8081:8081 -d tpp:temp
                    """
                }
            }
        }
    }
    
}
